/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ActivityLogsRouteImport } from './routes/activity-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsClientIdRouteImport } from './routes/clients_.$clientId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogsRoute = ActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients_/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/deals': typeof DealsRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/proposals': typeof ProposalsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/deals': typeof DealsRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/proposals': typeof ProposalsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/calendar': typeof CalendarRoute
  '/clients': typeof ClientsRoute
  '/deals': typeof DealsRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/meetings': typeof MeetingsRoute
  '/onboarding': typeof OnboardingRoute
  '/proposals': typeof ProposalsRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/clients_/$clientId': typeof ClientsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-logs'
    | '/calendar'
    | '/clients'
    | '/deals'
    | '/issues'
    | '/login'
    | '/media'
    | '/meetings'
    | '/onboarding'
    | '/proposals'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-logs'
    | '/calendar'
    | '/clients'
    | '/deals'
    | '/issues'
    | '/login'
    | '/media'
    | '/meetings'
    | '/onboarding'
    | '/proposals'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/activity-logs'
    | '/calendar'
    | '/clients'
    | '/deals'
    | '/issues'
    | '/login'
    | '/media'
    | '/meetings'
    | '/onboarding'
    | '/proposals'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/clients_/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogsRoute: typeof ActivityLogsRoute
  CalendarRoute: typeof CalendarRoute
  ClientsRoute: typeof ClientsRoute
  DealsRoute: typeof DealsRoute
  IssuesRoute: typeof IssuesRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  MeetingsRoute: typeof MeetingsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProposalsRoute: typeof ProposalsRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-logs': {
      id: '/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof ActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients_/$clientId': {
      id: '/clients_/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogsRoute: ActivityLogsRoute,
  CalendarRoute: CalendarRoute,
  ClientsRoute: ClientsRoute,
  DealsRoute: DealsRoute,
  IssuesRoute: IssuesRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  MeetingsRoute: MeetingsRoute,
  OnboardingRoute: OnboardingRoute,
  ProposalsRoute: ProposalsRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
